### PR TITLE
[Fix] DARP wasn't applied when using ReMixMatch.

### PR DESCRIPTION
**Pull request by PM25**
## What does this PR do?

Hi, I found the DARP method was not applied when using ReMixMatch as the base algorithm. The train_step() function in both the ReMixMatch and DARP classes did not reference the "PseudoLabelingHook". In order to address this issue, I made a modification to the ReMixMatch class so that it will check and apply DARP after the Distribution Alignment.

### Does your PR introduce any breaking changes? If yes, please list them.

The changes had an impact on the results of ReMixMatch + DARP, and did not have any effect on other configurations.

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you list all the **breaking changes** introduced by this pull request?

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

### CODE REVIEW

**Comment by Hhhhhhao** [comment]
Can you check the performance on CIFAR-10 after the modification? We need to make sure that the modified code won't affect the performance.

**Comment by PM25** [comment]
Hi, would you need the complete CIFAR10 results, or would a few selected settings be sufficient? If the latter is acceptable, I can provide you with the results in a few days.

As for the concern about the modified code, do you have any suggestions on how to improve it? I am also aware that this design is not ideal, but I don't have any better ideas on how to modify it.

**Comment by Hhhhhhao** [comment]
> Hi, would you need the complete CIFAR10 results, or would a few selected settings be sufficient? If the latter is acceptable, I can provide you with the results in a few days.
> 
> As for the concern about the modified code, do you have any suggestions on how to improve it? I am also aware that this design is not ideal, but I don't have any better ideas on how to modify it.

Currently I don't have good idea on this. That's probably why DARP was not applied on ReMixMatch (and other two algorithms that need pseudo-labeling I think). Let's think more about this and comp up a more appropriate way for doing this. 
We might need to separate some part of the functions in train_step into registrable functions thus we can re-specify those in imbalanced algorithms.

**Comment by PM25** [comment]
I think I have found a better solution to address the problem by referencing to the implementation in [FixMatch](https://github.com/microsoft/Semi-supervised-learning/tree/57dd2bf9be0ef32f3dc723e2128cf91a55d1dbad/semilearn/algorithms/fixmatch/fixmatch.py?plain=1#L78-L81). Specifically, I have added an code to check whether the "PseudoLabelingHook" is registered. If the PseudoLabelingHook is registered, it will be applied right after the Distribution Alignment in ReMixMatch. This modification should fix the issue with imbalanced algorithms that use PseudoLabelingHook in their method.

However, this modification may affect performance. I ran ReMixMatch+DARP three times for each setting using random seeds 0, 1, and 2, and averaged the top1-accuracy results. The results are shown below:

|          | cifar10_lb1500_100_ulb3000_-100 | cifar10_lb1500_100_ulb3000_100 |
| -------- | ----------------------- | ---------------------- |
| Original | 70.03±0.38             | 79.20±0.41            |
| Modified    | 67.56±0.43             | 78.21±0.45            |

Complete log files: https://drive.google.com/drive/folders/1nh4MjFuzViSmjMDpayDgzAFTN7osuqF6?usp=sharing

**Comment by Hhhhhhao** [comment]
> I think I have found a better solution to address the problem by referencing to the implementation in [FixMatch](https://github.com/microsoft/Semi-supervised-learning/tree/57dd2bf9be0ef32f3dc723e2128cf91a55d1dbad/semilearn/algorithms/fixmatch/fixmatch.py?plain=1#L78-L81). Specifically, I have added an code to check whether the "PseudoLabelingHook" is registered. If the PseudoLabelingHook is registered, it will be applied right after the Distribution Alignment in ReMixMatch. This modification should fix the issue with imbalanced algorithms that use PseudoLabelingHook in their method.
> 
> However, this modification may affect performance. I ran ReMixMatch+DARP three times for each setting using random seeds 0, 1, and 2, and averaged the top1-accuracy results. The results are shown below:
> 
> cifar10_lb1500_100_ulb3000_-100	cifar10_lb1500_100_ulb3000_100
> Original	70.03±0.38	79.20±0.41
> Modified	67.56±0.43	78.21±0.45
> Complete log files: https://drive.google.com/drive/folders/1nh4MjFuzViSmjMDpayDgzAFTN7osuqF6?usp=sharing

Looks like a plan. Let's maintain this pull request. We will merge it for the next update on Robust semi-supervised learning settings.

**Comment by PM25** [comment]
Sounds good, thanks!

**Pull request closed without merging**
