### PR TITLE
[Bug] Fix Aim repo path and Add Aim flag argument

### PR DESCRIPTION
**Pull request by adamtupper**
## What does this PR do?

 - Fixes the hard-coded Aim repository path in the `AimHook` (#151).
 - Bumps `huggingface-hub` to version 0.14.1 to fix dependency issues with `transformers` version 4.30.0.

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you list all the **breaking changes** introduced by this pull request?

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

### CODE REVIEW

**Comment by Hhhhhhao** [comment]
> ## What does this PR do?
> * Fixes the hard-coded Aim repository path in the `AimHook` ([Aim repository path is hard-coded #151](https://github.com/microsoft/Semi-supervised-learning/issues/151)).
> * Bumps `huggingface-hub` to version 0.14.1 to fix dependency issues with `transformers` version 4.30.0.
> 
> ## Before submitting
> * [x]  Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
> * [x]  Did you read the [contributor guideline](https://github.com/Lightning-AI/lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
> * [x]  Did you make sure your **PR does only one thing**, instead of bundling different changes together?
> * [x]  Did you make sure to **update the documentation** with your changes? (if necessary)
> * [x]  Did you list all the **breaking changes** introduced by this pull request?
> 
> ## PR review
> Anyone in the community is welcome to review the PR. Before you start reviewing, make sure you have read the [review guidelines](https://github.com/Lightning-AI/lightning/wiki/Review-guidelines). In short, see the following bullet-list:
> 
> * [x]  Is this pull request ready for review? (if not, please submit in draft mode)
> * [ ]  Check that all items from **Before submitting** are resolved
> * [ ]  Make sure the title is self-explanatory and the description concisely explains the PR
> * [ ]  Add labels and milestones (and optionally projects) to the PR so it can be classified

Hi, the updates looks fine. Only one thing -- can you set the use_aim default as False and aim_dir also similarly as in wandb with default as save_dir?

Also let's set these things to default in train.py so we do not need to make so many changes to the config files.

Thanks!

**Comment by adamtupper** [comment]
Sure thing! Just to clarify,

- `use_aim` shouldn't be set in the (default) config files, only added to the argument parser in `train.py`?
- `use_aim` does currently default to False, and is only set to True if the user uses the `--use_aim` flag:

  ```python
  parser.add_argument(
        "--use_aim", action="store_true", help="Use aim to plot and save curves"
  )
  ```
  
  Is this what you meant?

- I could remove the `aim_repo` config value, and set the Aim repository directory to
  ```python
  save_dir = os.path.join(algorithm.args.save_dir, 'aim', algorithm.args.save_name)
  ```
  
  as you suggest. Would that be preferable?

Let me know if that works or if you have any questions/remarks. Then I'll make the changes.

Thanks!

**Comment by Hhhhhhao** [comment]
> Sure thing! Just to clarify,
> 
> * `use_aim` shouldn't be set in the (default) config files, only added to the argument parser in `train.py`?
> * `use_aim` does currently default to False, and is only set to True if the user uses the `--use_aim` flag:
>   ```python
>   parser.add_argument(
>         "--use_aim", action="store_true", help="Use aim to plot and save curves"
>   )
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   Is this what you meant?
> * I could remove the `aim_repo` config value, and set the Aim repository directory to
>   ```python
>   save_dir = os.path.join(algorithm.args.save_dir, 'aim', algorithm.args.save_name)
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   as you suggest. Would that be preferable?
> 
> Let me know if that works or if you have any questions/remarks. Then I'll make the changes.
> 
> Thanks!

Hi, I think the above modification looks good. Thanks!

**Comment by adamtupper** [comment]
I've made the above changes. However, I left the `use_aim` parameter in the config generator scripts to be consistent with the Tensorboard and W&B behaviour so that the next time the config files need to be regenerated `use_aim: False` will be added.

**Review by Hhhhhhao — APPROVED** [review]
The code doesn't affect the training thus approved/

**Pull request merged**
